const ValidateMessage = {
  required: "This field is required",
  name: "name is required",
  code: "code is required",
  email: "email is required",
  password: "password is required",
  title: "title is required",
  source: "source is required",
  type: "type is required",
  group: "group is required",
  rank: "rank is required",
  keep_place: "keep place is required",
  description: "description is required",
  start_date: "start_date is required",
  end_date: "end_date is required",
  file: "file is required",
  id_card: "id card is required",
  khmer_name: "khmer name is required",
  latin_name: "latin name is required",
  code_name: "code_name is required",
  age: "age is required",
  transaction_type: "transaction_type is required",
  date: "date is required",
  reason: "reason is required",
  meeting_type: "meeting_type is required",
  event_url: "evnet_url is required",
  staff: "staff is required",
  location: "location is required",
  description: "description is required",
  event_type: "event type is required",
  office: "office is required",
  username: "username is required",
  email: "email is required",
  role: "role is required",
  sort: "sort is required",
  sort_name: "sort_name is required",
  start_date: "start date is required",
  end_date: "end date is required",
  office_section: "office_section is required",
  workyear: "work year is required",
  office_section: "office section is required",
  number_in_list: "number in list is required",
  dob: "date of birth is required",
  sex: "sex is required",
  religion: "religion is required",
  nationality: "nationality is required",
  living_status: "living status is required",
  address: "address is required",
  office_or_section: "Office/Section is required",
  role_position: "Role/Position is required",
  framework: "framework is required",
  join_date: "join date is required",
  join_current_position_date: "join current position date is required",
  ranks: "ranks is required",
  number_of_ranks: "number of ranks is required",
  year_of_ranks: "year of ranks is required",

  province: "province is required",
  district: "district is required",
  village: "village is required",
  commune: "commune is required",

  // organization: "organization is required",
  // role: "role is required",
  phone: "phone is required",
  receiver: "receiver is required",
  sending_date: "sending date is required",
  category: "category is required",
};

export default ValidateMessage;
